# Site settings
title: Feminist Book Club
email: 
description: > # this means to ignore newlines until "baseurl:"
 This is an eight (8) week book club/discussion group. Girl power!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
